version: '3.7'
services:
  db:
    image: mysql:8.0
    container_name: "database"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d/
    networks:
      - proxy

  web:
    build: ./web
    container_name: "web"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./web:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    networks:
      - proxy

  recommend:
    container_name: "recommend"
    build: ./recommend
    command: flask run --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./recommend:/recommend
    stdin_open: true
    tty: true
    networks:
      - proxy

networks:
  proxy:
    external: true
